# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='newField',
            field=models.CharField(default='newfield', max_length=20),
            preserve_default=False,
        ),
    ]
