# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20170409_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='newField',
        ),
        migrations.RemoveField(
            model_name='device',
            name='token',
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(choices=[('1', 'Room'), ('2', 'Living'), ('3', 'Dining')], max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
